import { Attributes, size } from '@mezon/mobile-ui';
import { StyleSheet } from 'react-native';

export const style = (colors: Attributes) =>
	StyleSheet.create({
		transferVisual: {
			position: 'relative',
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'center',
			paddingTop: size.s_28,
			paddingBottom: size.s_20,
		},
		userCircle: {
			width: size.s_80,
			height: size.s_80,
			borderRadius: size.s_30,
			alignItems: 'center',
			justifyContent: 'center',
		},
		defaultAvatar: {
			width: size.s_50,
			height: size.s_50,
			borderRadius: size.s_26,
			alignItems: 'center',
			justifyContent: 'center',
		},
		avatarText: {
			fontSize: size.s_20,
			fontWeight: '600',
			color: colors.white,
		},
		arrowContainer: {
			position: 'absolute',
			top: 0,
			marginHorizontal: size.s_20,
			width: size.s_80,
			height: size.s_20,
			borderWidth: size.s_2,
			borderColor: colors.white,
			borderStyle: 'dashed',
			alignItems: 'center',
			justifyContent: 'center',
			borderBottomWidth: 0
		},
		arrowDown: {
			position: 'absolute',
			right: -8,
			bottom: 0,
			width: 0,
			height: 0,
			borderLeftWidth: size.s_6,
			borderRightWidth: size.s_6,
			borderTopWidth: size.s_8,
			borderLeftColor: 'transparent',
			borderRightColor: 'transparent',
			borderTopColor: colors.white,
		},
		serverName: {
			textAlign: 'center',
			fontSize: size.medium,
			fontWeight: '700',
			color: colors.text,
			marginBottom: size.s_20,
		},
		warningText: {
			textAlign: 'center',
			fontSize: size.s_14,
			fontWeight: '400',
			color: colors.textStrong,
			lineHeight: 1.4 * size.s_16,
			marginBottom: size.s_20,
		},
		highlightText: {
			color: colors.white,
			fontWeight: '700',
		},
		acknowledgmentSection: {
			marginVertical: size.s_20,
		},
		sectionTitle: {
			fontSize: size.s_12,
			fontWeight: '600',
			color: colors.textDisabled,
			marginBottom: size.s_20,
			textTransform: 'uppercase',
		},
		checkboxContainer: {
			flexDirection: 'row',
			alignItems: 'center',
			borderRadius: size.s_10,
			backgroundColor: colors.secondary,
			padding: size.s_8,
		},
		checkbox: {
			width: size.s_20,
			height: size.s_20,
			borderRadius: size.s_10,
			borderWidth: 2,
			borderColor: colors.white,
			alignItems: 'center',
			justifyContent: 'center',
			marginRight: size.s_12,
			marginTop: size.s_2,
		},
		checkboxChecked: {
			backgroundColor: colors.bgViolet,
			borderColor: colors.white,
		},
		acknowledgmentText: {
			flex: 1,
			fontSize: size.s_14,
			fontWeight: '400',
			color: colors.textStrong,
			lineHeight: 1.4 * size.s_16,
		},
		button: {
			borderRadius: size.s_20,
			backgroundColor: colors.bgViolet,
			padding: size.s_10,
			marginBottom: size.s_20,
		},
		buttonDisabled: {
			backgroundColor: colors.textDisabled,
			opacity: 0.5,
		},
		textButton: {
			fontWeight: '500',
			textAlign: 'center',
			fontSize: size.s_14,
			color: colors.white,
		},
	});
