# GitLeaks Configuration File

# Title for the configuration
title = "Mezon GitLeaks Configuration"

# Global settings
[allowlist]
  description = "Global allowlist"
  paths = [
    "**/*.snap",
    "**/*.svg",
    "**/*.lock",
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**"
  ]

# Rules for detecting secrets
[[rules]]
  id = "generic-api-key"
  description = "Generic API Key"
  regex = '''(?i)(?:api(?:[-_]?key)?|token|key)(?:[-_]?token)?[\s]*(?:=|:|:=|=>)[\s]*["'`]([a-zA-Z0-9=+/]{16,})(?:["'`]|$)'''
  tags = ["key", "API", "generic"]
  [rules.allowlist]
    description = "Exclude test files"
    paths = ["**/test/**"]

[[rules]]
  id = "aws-access-key"
  description = "AWS Access Key ID"
  regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
  tags = ["key", "AWS"]

[[rules]]
  id = "aws-secret-key"
  description = "AWS Secret Access Key"
  regex = '''(?i)aws[\s\S]{0,20}['\"][0-9a-zA-Z\/+]{40}['\"]'''
  tags = ["key", "AWS"]

[[rules]]
  id = "firebase-key"
  description = "Firebase API Key"
  regex = '''(?i)(?:firebase|fb)(?:[0-9a-z\-_\t .]{0,20})(?:[\'\"\s]*(?:=|>|:)[\'\"\s]*)(?:[0-9a-z\-_=]{24})'''
  tags = ["key", "Firebase"]

[[rules]]
  id = "private-key"
  description = "Private Key"
  regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
  tags = ["key", "private"]

[[rules]]
  id = "password-in-code"
  description = "Password in code"
  regex = '''(?i)(password|passwd|pwd)\s*[=:]\s*["']([^"']{4,})(?<!PLACEHOLDER|PASSWORD|CHANGEME|EXAMPLE)["']'''
  tags = ["password"]
  [rules.allowlist]
    description = "Exclude test files and examples"
    regexes = ["(?i)example|placeholder|changeme|dummy"]

[[rules]]
  id = "env-var"
  description = "Environment Variable"
  file = '''(?i)(\.env|\.env\..*|\.env-.*|.*\.env)$'''
  regex = '''(?i)(?:api_key|api_secret|token|secret|password|passwd|pwd|key)\s*=\s*["']?([^"'\s][^"']{4,})["']?'''
  tags = ["env", "key"]
  [rules.allowlist]
    description = "Exclude example files"
    paths = ["**/*.example", "**/*.sample", "**/example/**"]